name: Release
on:
  release:
    types: [created]

permissions: write-all

jobs:
  release-macos:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Target Platform to macOS Silicon
        run: rustup target add aarch64-apple-darwin

      - name: Build for macOS
        run: |
          cargo build --release --target aarch64-apple-darwin

      - name: Upload macOS Artifact
        run: |
          export ZIP_FILE_NAME="helix-ts-gen-${{ github.event.release.tag_name }}-aarch64-apple-darwin.zip"
          mkdir -p release_package
          cp target/aarch64-apple-darwin/release/helix-ts-gen release_package/
          cd release_package
          zip -r $ZIP_FILE_NAME *
          gh release upload ${{ github.event.release.tag_name }} $ZIP_FILE_NAME
        env:
          GH_TOKEN: ${{ github.token }}
